CREATE TABLE  SZBDC_TRIGGER_INFO (
  ID NUMBER NOT NULL,
  JOB_GROUP NUMBER NOT NULL,
  JOB_CRON VARCHAR2(128) NOT NULL,
  JOB_DESC VARCHAR2(255) NOT NULL,
  ADD_TIME DATE DEFAULT NULL,
  UPDATE_TIME DATE DEFAULT NULL,
  AUTHOR VARCHAR2(64) DEFAULT NULL,
  ALARM_EMAIL VARCHAR2(255) DEFAULT NULL,
  EXECUTOR_ROUTE_STRATEGY VARCHAR2(50) DEFAULT NULL,
  EXECUTOR_HANDLER VARCHAR2(255) DEFAULT NULL,
  EXECUTOR_PARAM VARCHAR2(512) DEFAULT NULL,
  EXECUTOR_BLOCK_STRATEGY VARCHAR2(50) DEFAULT NULL,
  EXECUTOR_TIMEOUT NUMBER DEFAULT 0 NOT NULL ,
  EXECUTOR_FAIL_RETRY_COUNT NUMBER DEFAULT 0 NOT NULL,
  GLUE_TYPE VARCHAR2(50) NOT NULL,
  GLUE_SOURCE VARCHAR2(512),
  GLUE_REMARK VARCHAR2(128) DEFAULT NULL,
  GLUE_UPDATETIME DATE DEFAULT NULL,
  CHILD_JOBID VARCHAR2(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE S_SZBDC_TRIGGER_INFO;

COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."JOB_CRON" IS '任务执行CRON';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."AUTHOR" IS '作者';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."ALARM_EMAIL" IS '报警邮件';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."EXECUTOR_ROUTE_STRATEGY" IS '执行器路由策略';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."EXECUTOR_BLOCK_STRATEGY" IS '阻塞处理策略';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."EXECUTOR_TIMEOUT" IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."EXECUTOR_FAIL_RETRY_COUNT" IS '失败重试次数';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."GLUE_REMARK" IS 'GLUE备注';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."GLUE_UPDATETIME" IS 'GLUE更新时间';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_INFO"."CHILD_JOBID" IS '子任务ID，多个逗号分隔';


---
CREATE TABLE  SZBDC_TRIGGER_LOG (
  ID NUMBER NOT NULL,
  JOB_GROUP NUMBER NOT NULL,
  JOB_ID NUMBER NOT NULL,
  EXECUTOR_ADDRESS VARCHAR2(255) DEFAULT NULL,
  EXECUTOR_HANDLER VARCHAR2(255) DEFAULT NULL,
  EXECUTOR_PARAM VARCHAR2(512) DEFAULT NULL,
  EXECUTOR_SHARDING_PARAM VARCHAR2(20) DEFAULT NULL,
  EXECUTOR_FAIL_RETRY_COUNT NUMBER DEFAULT 0,
  TRIGGER_TIME Date DEFAULT NULL,
  TRIGGER_CODE NUMBER,
  TRIGGER_MSG VARCHAR2(512),
  HANDLE_TIME Date DEFAULT NULL,
  HANDLE_CODE NUMBER,
  HANDLE_MSG VARCHAR2(512),
  ALARM_STATUS NUMBER DEFAULT 0,
  PRIMARY KEY (ID,TRIGGER_TIME,HANDLE_CODE)
);

CREATE SEQUENCE S_SZBDC_TRIGGER_LOG;

COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."EXECUTOR_ADDRESS" IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."EXECUTOR_SHARDING_PARAM" IS '执行器任务分片参数，格式如 1/2';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."EXECUTOR_FAIL_RETRY_COUNT" IS '失败重试次数';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."TRIGGER_TIME" IS '调度-时间';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."TRIGGER_CODE" IS '调度-结果';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."TRIGGER_MSG" IS '调度-日志';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."HANDLE_TIME" IS '执行-时间';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."HANDLE_CODE" IS '执行-状态';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."HANDLE_MSG" IS '执行-日志';
COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOG"."ALARM_STATUS" IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';


CREATE TABLE  SZBDC_TRIGGER_LOGGLUE (
  ID NUMBER NOT NULL,
  JOB_ID NUMBER NOT NULL,
  GLUE_TYPE VARCHAR2(50) DEFAULT NULL,
  GLUE_SOURCE VARCHAR2(200),
  GLUE_REMARK VARCHAR2(128) NOT NULL,
  ADD_TIME TIMESTAMP DEFAULT NULL,
  UPDATE_TIME TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE S_SZBDC_TRIGGER_LOGGLUE;

COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOGGLUE"."JOB_ID" IS '任务，主键ID';

COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOGGLUE"."GLUE_TYPE" IS 'GLUE类型';

COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOGGLUE"."GLUE_SOURCE" IS 'GLUE源代码';

COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_LOGGLUE"."GLUE_REMARK" IS 'GLUE备注';


CREATE TABLE  SZBDC_TRIGGER_REGISTRY (
  ID NUMBER NOT NULL,
  REGISTRY_GROUP VARCHAR2(255) NOT NULL,
  REGISTRY_KEY VARCHAR2(255) NOT NULL,
  REGISTRY_VALUE VARCHAR2(255) NOT NULL,
  UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE S_SZBDC_TRIGGER_REGISTRY;


CREATE TABLE  SZBDC_TRIGGER_GROUP (
  ID NUMBER NOT NULL,
  APP_NAME VARCHAR2(64) NOT NULL,
  TITLE VARCHAR2(24) NOT NULL,
  "ORDER" NUMBER DEFAULT 0 not null,
  ADDRESS_TYPE NUMBER DEFAULT 0,
  ADDRESS_LIST VARCHAR2(512),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE S_SZBDC_TRIGGER_GROUP;

COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_GROUP"."APP_NAME" IS '执行器AppName';

COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_GROUP"."TITLE" IS '执行器名称';

COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_GROUP"."ORDER" IS '排序';

COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_GROUP"."ADDRESS_TYPE" IS '执行器地址类型：0=自动注册、1=手动录入';

COMMENT ON COLUMN "SZBDC_ONLINEBOOK"."SZBDC_TRIGGER_GROUP"."ADDRESS_LIST" IS '执行器地址列表，多地址逗号分隔';



CREATE TABLE  SZBDC_JOB_DETAILS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    JOB_NAME  VARCHAR2(200) NOT NULL,
    JOB_GROUP VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(250) NULL,
    JOB_CLASS_NAME   VARCHAR2(250) NOT NULL,
    IS_DURABLE VARCHAR2(1) NOT NULL,
    IS_NONCONCURRENT VARCHAR2(1) NOT NULL,
    IS_UPDATE_DATA VARCHAR2(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR2(1) NOT NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
);


CREATE TABLE  SZBDC_TRIGGERS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    JOB_NAME  VARCHAR2(200) NOT NULL,
    JOB_GROUP VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(250) NULL,
    NEXT_FIRE_TIME NUMBER(13) NULL,
    PREV_FIRE_TIME NUMBER(13) NULL,
    PRIORITY NUMBER NULL,
    TRIGGER_STATE VARCHAR2(16) NOT NULL,
    TRIGGER_TYPE VARCHAR2(8) NOT NULL,
    START_TIME NUMBER(13) NOT NULL,
    END_TIME NUMBER(13) NULL,
    CALENDAR_NAME VARCHAR2(200) NULL,
    MISFIRE_INSTR NUMBER NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE  SZBDC_SIMPLE_TRIGGERS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    REPEAT_COUNT NUMBER(7) NOT NULL,
    REPEAT_INTERVAL NUMBER(12) NOT NULL,
    TIMES_TRIGGERED NUMBER(10) NOT NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE  SZBDC_CRON_TRIGGERS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    CRON_EXPRESSION VARCHAR2(200) NOT NULL,
    TIME_ZONE_ID VARCHAR2(80),
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE  SZBDC_SIMPROP_TRIGGERS
  (          
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    STR_PROP_1 VARCHAR2(512) NULL,
    STR_PROP_2 VARCHAR2(512) NULL,
    STR_PROP_3 VARCHAR2(512) NULL,
    INT_PROP_1 NUMBER NULL,
    INT_PROP_2 NUMBER NULL,
    LONG_PROP_1 NUMBER NULL,
    LONG_PROP_2 NUMBER NULL,
    DEC_PROP_1 NUMERIC(13,4) NULL,
    DEC_PROP_2 NUMERIC(13,4) NULL,
    BOOL_PROP_1 VARCHAR2(1) NULL,
    BOOL_PROP_2 VARCHAR2(1) NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE  SZBDC_BLOB_TRIGGERS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    BLOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE  SZBDC_CALENDARS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    CALENDAR_NAME  VARCHAR2(200) NOT NULL,
    CALENDAR BLOB NOT NULL,
    PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
);

CREATE TABLE  SZBDC_PAUSED_TRIGGER_GRPS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_GROUP  VARCHAR2(200) NOT NULL, 
    PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP)
);


CREATE TABLE  SZBDC_FIRED_TRIGGERS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    ENTRY_ID VARCHAR2(95) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    INSTANCE_NAME VARCHAR2(200) NOT NULL,
    FIRED_TIME NUMBER(13) NOT NULL,
    SCHED_TIME NUMBER(13) NOT NULL,
    PRIORITY NUMBER NOT NULL,
    STATE VARCHAR2(16) NOT NULL,
    JOB_NAME VARCHAR2(200) NULL,
    JOB_GROUP VARCHAR2(200) NULL,
    IS_NONCONCURRENT VARCHAR2(1) NULL,
    REQUESTS_RECOVERY VARCHAR2(1) NULL,
    PRIMARY KEY (SCHED_NAME,ENTRY_ID)
);

CREATE TABLE  SZBDC_SCHEDULER_STATE
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    INSTANCE_NAME VARCHAR2(200) NOT NULL,
    LAST_CHECKIN_TIME NUMBER(13) NOT NULL,
    CHECKIN_INTERVAL NUMBER(13) NOT NULL,
    PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
);

CREATE TABLE  SZBDC_LOCKS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    LOCK_NAME  VARCHAR2(40) NOT NULL, 
    PRIMARY KEY (SCHED_NAME,LOCK_NAME)
);



/*
INSERT INTO SZBDC_TRIGGER_GROUP(id, app_name, title, order, addresSZBDC_type, addresSZBDC_list) VALUES (1, 'xxl-job-executor-sample', '示例执行器', 1, 0, NULL);
INSERT INTO SZBDC_TRIGGER_INFO(id, job_group, job_cron, job_desc, add_time, update_time, author, alarm_email, executor_route_strategy, executor_handler, executor_param, executor_block_strategy, executor_timeout, executor_fail_retry_count, glue_type, glue_source, glue_remark, glue_updatetime, child_jobid) VALUES (1, 1, '0 0 0 * * ? *', '测试任务1', '2018-11-03 22:21:31', '2018-11-03 22:21:31', 'XXL', '', 'FIRST', 'demoJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', '2018-11-03 22:21:31', '');

commit;
*/
/*
drop table SZBDC_JOB_DETAILS;
drop table SZBDC_TRIGGERS;
drop table SZBDC_SIMPLE_TRIGGERS;
drop table SZBDC_CRON_TRIGGERS;
drop table SZBDC_SIMPROP_TRIGGERS;
drop table SZBDC_BLOB_TRIGGERS;
drop table SZBDC_CALENDARS;
drop table SZBDC_PAUSED_TRIGGER_GRPS;
drop table SZBDC_FIRED_TRIGGERS;
drop table SZBDC_SCHEDULER_STATE;
drop table SZBDC_LOCKS;
drop table SZBDC_TRIGGER_INFO;
drop table SZBDC_TRIGGER_LOG;
drop table SZBDC_TRIGGER_LOGGLUE;
drop table SZBDC_TRIGGER_REGISTRY;
drop table SZBDC_TRIGGER_GROUP;
*/